# Generated by Django 3.1.7 on 2021-05-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesCreater', '0005_auto_20210510_0215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
